### ISSUE TITLE
I need help, I couldn't find this folder (feeds/packages/net/openvpn/patches) in my router

### ISSUE THREAD

**Issue by birdycoachingeg** [egc112/openvpn-scramble#1]
I'm new to openwrt system installed in TP-Link Archer C7 v5 router
I have installed openvpn-openssl but when accessing my openwrt to copy 2.5 folder files I can't find feeds/packages/net/openvpn/patches
How could I fix this problem please?

**Comment by egc112** [comment]
These patches are for when you compile your own build, they do not run on existing firmware.
https://openwrt.org/docs/guide-developer/toolchain/use-buildsystem

**Comment by birdycoachingeg** [comment]
where to upload ovpn file my friend because openvpn is not having this option 
now I have compiled my own build like you said but didn't know where to upload my config.
![Screenshot 2024-01-01 104152](https://github.com/egc112/OpenWRT-OpenVPN-scramble/assets/142119094/5a869e32-6588-40b8-9ddb-e0d8f777623e)

**Comment by birdycoachingeg** [comment]
hi my brother, after compiling my own build and uploading ovpn file and all the steps there to allow vpn in firewall
https://support.surfshark.com/hc/en-us/articles/13114753629970-How-to-set-up-OpenVPN-on-OpenWRT-using-the-router-s-web-interface
![Screenshot 2024-01-01 112218](https://github.com/egc112/OpenWRT-OpenVPN-scramble/assets/142119094/486c6451-1fdf-4344-aba9-cbb7f6d2f94c)

after pressing start, it started but my ip still the same not changed
what is the problem there ?
and I really need to say thanks for your help and also your great effort here

**Comment by egc112** [comment]
the log usually will show what is the problem, from the command line use:
`logread`
But these questions can better be answered on the openwrt forum, I suggest you make a new thread about your openvpn setup in this forum: https://forum.openwrt.org/c/general/6

**Comment by birdycoachingeg** [comment]
okay my friend I will
but how to make sure that scramble option is successfully added to my router setup because I guess the problem may be from it
because my country blocked openvpn and I must use scramble option to get rid of it

**Comment by birdycoachingeg** [comment]
when run strings /usr/sbin/openvpn | grep scramble in putty 
this message appears to me

scramble
WARNING: No recognized 'scramble' method specified; using 'scramble xormask "%s"'
No recognized 'scramble' method specified or extra parameters for 'scramble'

scramble is not loaded, right?

**Comment by egc112** [comment]
scramble is not enabled by default.
You have to add one of the scramble options in your openvpn config e.g.:
`scramble xormask "password"`

As outlined in the [instructions](https://github.com/egc112/OpenWRT-egc-add-on/blob/main/patches/openvpn-scramble/Add%20OpenVPN%20Scramble%20XOR.md)

First setup with scramble disabled (so no scramble options in the config) and if that works enable scramble options on both client and server
