### ISSUE TITLE
Scramble option is missing in openvpn.options and not recognized in ovpn file !

### ISSUE THREAD

**Issue by Bebooo43** [egc112/openvpn-scramble#3]
Hello, I've been trying to build openvpn opessl and mbedtls for OpenWRT 21.02 (OpenVPN 2.5.3) and OpenWRT 23.05 (OpenVPN 2.5.8) both were failing for target aarch64 cortex a53.

I've also checked the pre-compiled packages in the following article that credited this repo. it also missing the parameter and does not work on my router.

https://scramblevpn.wordpress.com/2024/07/02/compile-patched-openvpn-ipk-package-for-openwrt-router/

I've also tried to check the compiled src files, it appears the patches are being applied correctly but for some reason are not included in the final builds.

<img width="576" alt="Screenshot 2024-12-23 at 12 24 39 PM" src="https://github.com/user-attachments/assets/ee069545-9af7-4c75-86a4-5043da0bdc0e" />

**Comment by egc112** [comment]
It is not an option you can set via the GUI.
You have to set the scramble option in the openvpn config file.
For a quick check to see if the scramble options are present in your build, from commandline:
`strings /usr/sbin/openvpn | grep scramble`

you can also check in the `build_dir`:
`/linuxdata/openwrt/build_dir/target-aarch64_cortex-a53_musl/openvpn-openssl/openvpn-2.6.12/src/openvpn`  
If the patches are applied `grep xor forward.c`
```
egc@egc-VirtualBox:/linuxdata/openwrt/build_dir/target-aarch64_cortex-a53_musl/openvpn-openssl/openvpn-2.6.12/src/openvpn$  grep xor forward.c
                              c->options.ce.xormethod,
                              c->options.ce.xormask,
                              c->options.ce.xormasklen);
                                         c->options.ce.xormethod,
                                         c->options.ce.xormask,
                                         c->options.ce.xormasklen);
egc@egc-VirtualBox:/linuxdata/openwrt/build_dir/target-aarch64_cortex
```

I did not test it on versions which are EOL so only on 23.05.5 and higher with OpenVPN OpenSSL.

Current repo is: https://github.com/egc112/OpenWRT-egc-add-on/tree/main/openvpn-scramble

**Comment by Bebooo43** [comment]
Thanks bro for the info. I figured out the binary has the scramble option by `strings /usr/sbin/openvpn | grep scramble` command. But it was not recognized in the ovpn config for some reason ! I've fixed it by adding the scramble manually to `usr/share/openvpn.options` and replacing the installed binary in `/usr/sbin/openvpn` with the correct one. 

I think it was not working after installing the ipk due to existing packages depend on the openvpn-openssl.
It was a small difference between old 2.4 ipk and the new compiled packages in the `openvpn.options`.

**Comment by egc112** [comment]
Great to hear it is working 👍 

There is no need to replace the openvpn.options as it is not intended to be in there as you can simply add the options in the openvpn config file:
![afbeelding](https://github.com/user-attachments/assets/84c6bff4-34a3-404c-b03a-9513ce5501f3)
